version: '3.8'

services:
  api:
    build: .
    container_name: ispindel-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - influxdb
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: ispindel-influxdb
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

volumes:
  influxdb-data: